Dtdb\BuilderBundle\Entity\Comment:
    type: entity
    table: comment
    repositoryClass: Dtdb\BuilderBundle\Entity\CommentRepository
    manyToOne:
        author:
            targetEntity: Dtdb\UserBundle\Entity\User
            nullable: false
            inversedBy: comments
            joinColumn:
                name: user_id
                referencedColumnName: id
        decklist:
            targetEntity: Dtdb\BuilderBundle\Entity\Decklist
            nullable: false
            inversedBy: comments
            joinColumn:
                name: decklist_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        text:
            type: text
        creation:
            type: datetime
    lifecycleCallbacks: {  }
