Dtdb\CardsBundle\Entity\Gang:
    type: entity
    table: gang
    indexes:
        code_index:
            columns: [ code ]
    oneToMany:
        cards:
            targetEntity: Card
            mappedBy: gang
        decklists:
            targetEntity: Dtdb\BuilderBundle\Entity\Decklist
            mappedBy: gang
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
