Dtdb\CardsBundle\Entity\Type:
    type: entity
    table: type
    indexes:
        name_index:
            columns: [ name ]
    oneToMany:
        cards:
            targetEntity: Card
            mappedBy: type
    manyToOne:
        suit:
            targetEntity: Suit
            inversedBy: types
            joinColumn:
                name: suit_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
